spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: user
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: pass
    url: jdbc:h2:mem:testDB;DB_CLOSE_ON_EXIT=FALSE;IFEXISTS=FALSE;DB_CLOSE_DELAY=-1
    tomcat:
      max-active: 100
      max-idle: 8
      min-idle: 8
      max-wait: 25000
      initial-size: 20
      test-on-borrow: true
      test-on-return: false
    schema: classpath:/schema-h2.sql
    data: classpath:/data-h2.sql
  h2:
    console:
      enabled: true
      settings:
        trace: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
          hibernate.format_sql: true
          hibernate.use_sql_comments: true
          show-sql: true
  data:
    rest:
      base-path: /spring-data
  activemq:
      broker-url: failover://tcp://localhost:61616
      user: admin
      password: admin
server:
  port: 8083
logging:
  level:
    ROOT: DEBUG
    org.springframework: ERROR
    org.springframework.web: DEBUG
    org.springframework.jdbc.*: TRACE
    org.hibernate:
      SQL: DEBUG
      type: TRACE
      type.descriptor.sql: TRACE

jms:
  queue:
    destination: game_queue

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://user:user@localhost:8082/eureka}
    registry-fetch-interval-seconds: 5
  instance:
    preferIpAddress: true
feign:
  hystrix:
    enabled: false

endpoints:
  enabled: false
  health:
    enabled: true
  info:
    enabled: true
---
spring:
  profiles: prod
  application:
    name: user
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: pass
    url: jdbc:h2:mem:testDB;DB_CLOSE_ON_EXIT=FALSE;IFEXISTS=FALSE;DB_CLOSE_DELAY=-1
    tomcat:
      max-active: 100
      max-idle: 8
      min-idle: 8
      max-wait: 25000
      initial-size: 20
      test-on-borrow: true
      test-on-return: false
    schema: classpath:/schema-h2.sql
    data: classpath:/data-h2.sql
  h2:
    console:
      enabled: true
      settings:
        trace: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
          hibernate.format_sql: true
          hibernate.use_sql_comments: true
          show-sql: true
  data:
    rest:
      base-path: /spring-data
  activemq:
      broker-url: failover://tcp://activemq:61616
      user: admin
      password: admin
server:
  port: 8083
logging:
  level:
    ROOT: DEBUG
    org.springframework: ERROR
    org.springframework.web: DEBUG
    org.springframework.jdbc.*: TRACE
    org.hibernate:
      SQL: DEBUG
      type: TRACE
      type.descriptor.sql: TRACE

jms:
  queue:
    destination: game_queue

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://user:user@discovery:8082/eureka}
    registry-fetch-interval-seconds: 5
  instance:
    preferIpAddress: true
feign:
  hystrix:
    enabled: false

endpoints:
  enabled: false
  health:
    enabled: true
  info:
    enabled: true